### ISSUE TITLE
Fail to search in PDF

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#105]
Reproducer: click on a PDF, open the edit toolbar, click on the search entry, type a word to search for.

Expected result: words searched for and highlighted.

Observed result: nothing seen, except for logs;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Browse.activity/edittoolbar.py", line 159, in __search_entry_changed_cb
    self._find_and_mark_text(entry)
  File "/usr/share/sugar/activities/Browse.activity/edittoolbar.py", line 149, in _find_and_mark_text
    controller = self._browser.get_find_controller()
AttributeError: 'DummyBrowser' object has no attribute 'get_find_controller'
```

**Comment by quozl** [comment]
8c66ce05fba927879fef6bca86e37be497ab04a5
