### ISSUE TITLE
Sometimes fails to download and show PDF

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#106]
```log
1568155200.231043 ERROR root: FINISHED file:///home/guest/Downloads/Carolyn_FINAL_DRAFT_OWL_1_.pdf
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Browse.activity/pdfviewer.py", line 555, in __download_finished_cb
    self._show_pdf()
  File "/usr/share/sugar/activities/Browse.activity/pdfviewer.py", line 482, in _show_pdf
    self._evince_viewer = EvinceViewer(self._pdf_uri)
  File "/usr/share/sugar/activities/Browse.activity/pdfviewer.py", line 66, in __init__
    self._doc = EvinceDocument.Document.factory_get_document(uri)
gi.repository.GLib.Error: g-io-error-quark: Error opening file /home/guest/Downloads/Carolyn_FINAL_DRAFT_OWL_1_.pdf: No such file or directory (1)
1568155200.236871 ERROR root: FINISHED file:///home/guest/Downloads/Carolyn_FINAL_DRAFT_OWL_1_.pdf

```

URL was
https://wiki.sugarlabs.org/go/File:Carolyn_FINAL_DRAFT_OWL_1_.pdf
which contains link to a PDF
https://wiki.sugarlabs.org/images/b/b0/Carolyn_FINAL_DRAFT_OWL_1_.pdf

**Comment by chimosky** [comment]
This is difficult to reproduce, I've tried and the document opens.

**Comment by quozl** [comment]
Thanks for testing.  Yes, it only happens sometimes, so it may be a [race condition](https://en.wikipedia.org/wiki/Race_condition) that depends on network latency or other operations on the same computer.

I've tested again.  In 32 attempts on a single core QEMU VM, the traceback happened once.  It also happened once in 36 attempts on an eight core QEMU VM on an eight core system.

```log
Traceback (most recent call last):
  File "/usr/src/sugar-activities/Browse.activity/pdfviewer.py", line 555, in __download_finished_cb
    self._show_pdf()
  File "/usr/src/sugar-activities/Browse.activity/pdfviewer.py", line 482, in _show_pdf
    self._evince_viewer = EvinceViewer(self._pdf_uri)
  File "/usr/src/sugar-activities/Browse.activity/pdfviewer.py", line 66, in __init__
    self._doc = EvinceDocument.Document.factory_get_document(uri)
gi.repository.GLib.Error: g-io-error-quark: Error opening file /home/guest/Carolyn_FINAL_DRAFT_OWL_1_.pdf: No such file or directory (1)
```

I've proved that the XDG directories don't need to exist for this traceback to occur.  In the first traceback in the opening comment, the _Downloads_ directory is referenced.  In this second traceback, it is not.  The Downloads directory can be created by running the `xdg-user-dirs-update` command in Terminal.

We don't need to reproduce in order to find and fix a problem, but it would sure help.

**Comment by Saumya-Mishra9129** [comment]
I am able to reproduce it in alternate attempts. It is somewhat similiar error as in toolkit - https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/441
