### ISSUE TITLE
The tab crashes when the embedded video is played in the browser.

### ISSUE THREAD

**Issue by sourabhaa** [sugarlabs/browse-activity#116]
**log of browser-activity**
1616407200.059666 ERROR root: WebKit2 WebView at uri 'https://www.youtube.com/' has crashed
1616407240.945007 ERROR root: WebKit2 WebView at uri 'https://www.google.com/intl/en_in/earth/' has crashed
1616409426.245211 ERROR root: WebKit2 WebView at uri 'https://github.com/' has crashed
Traceback (most recent call last):
  File "/home/osl18/Activities/Browse.activity/browser.py", line 319, in __crashed_cb
    self.close_tab(browser.get_parent())
  File "/home/osl18/Activities/Browse.activity/browser.py", line 390, in close_tab
    tab_page.props.browser.destroy()
AttributeError: 'gi._gi.GProps' object has no attribute 'browser'
Normal successful completion, pid 55637 activity_id 34a3b6c4906ee27d31fac4619bdfe9eaaaebceaf

Reproduce:
1. Open browser-activity, type www.youtube.com and  play a video. (or)
2. Search something(on Google) that shows video suggestions and hover the cursor over it for a bit. (or)
3. Open a web page with heavy graphics (homepage of GitHub) and scroll down half way.

![Browser-tab crashes](https://user-images.githubusercontent.com/43743186/111976593-ce88f680-8b27-11eb-9f83-79c2035b5b9d.jpeg)

**Comment by srevinsaju** [comment]
We should probably move to something better like a [Blink](https://en.wikipedia.org/wiki/Blink_(browser_engine)) Web Engine.
