### ISSUE TITLE
Fail to start using `sugar-activity` in Terminal

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#89]
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 214, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 48, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Browse.activity/webactivity.py", line 192, in __init__
    self._tabbed_view = TabbedView(self)
  File "/usr/share/sugar/activities/Browse.activity/browser.py", line 133, in __init__
    self.settings = _get_local_settings(activity)
  File "/usr/share/sugar/activities/Browse.activity/browser.py", line 117, in _get_local_settings
    _settings = Gio.Settings.new_full(schema, None, None)
TypeError: Argument 0 does not allow None as a value
Segmentation fault (core dumped)
```

May be caused by environment variables inherited from Terminal, which would mean the fix may also be done to Terminal.

Workaround: start from Sugar home view.

**Comment by aarjavjain1** [comment]
Is the issue still there or has been corrected by https://github.com/sugarlabs/terminal-activity/pull/34

If it persists, how to reproduce it?

Thanks.

**Comment by quozl** [comment]
Thanks.  I agree, it is fixed.  Method to reproduce per issue title; start Browse using `sugar-activity` in Terminal.
